apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitema-hinweis.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aitema-hinweis.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    {{- include "aitema-hinweis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.port }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitema-hinweis.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aitema-hinweis.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    {{- include "aitema-hinweis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.port }}
    protocol: TCP
