apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://hinschg_prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "30s"
      httpMethod: POST
    editable: false
